[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "slutil"
authors = [
    {name = "Eugene Prout", email = "eugene.prout1@gmail.com"},
]
description = "Command-line utility to view slurm jobs"
readme = "README.md"
requires-python = ">=3.7"
dynamic = ["dependencies", "version"]

[project.scripts]
slutil = "slutil.main:start_cli"

[tool.setuptools_scm]
local_scheme = "no-local-version"

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}