name: Semantic Release

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'CHANGELOG.md'
      - 'pyproject.toml'

jobs:
  release:
    runs-on: ubuntu-latest
    concurrency: release

    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.EP_PAT_ADMIN }}
        fetch-depth: 0

    - name: Python Semantic Release
      uses: relekang/python-semantic-release@master
      with:
        github_token: ${{ secrets.EP_PAT_ADMIN }}
        repository_username: __token__
        repository_password: ${{ secrets.PYPI_TOKEN }}
    
    - name: Publish distribution 📦 to ProutTech PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository_url: http://pypi.prout.tech
        user: eugene
        password: ${{ secrets.PYPI_PROUTTECH_PASS }}